stages:
  - init
  - validate
  - plan
  - apply

image: hashicorp/terraform:latest

variables:
  TF_ENV: "default"
  TF_WORKING_DIR: "."
  TF_VERSION: "1.10.5"

before_script:
  - echo "Ensuring correct Terraform version is installed..."
  - terraform --version
  - tfenv install $TF_VERSION
  - /bin/bash -c 'echo "Using bash shell..." && terraform --version'

terraform-init:
  stage: init
  script:
    - echo "Initializing Terraform for $TF_ENV environment..."
    - cd $TF_WORKING_DIR
    - terraform init
  only:
    - master

terraform-validate:
  stage: validate
  script:
    - echo "Validating Terraform configuration for $TF_ENV environment..."
    - cd $TF_WORKING_DIR
    - terraform validate
  only:
    - master

terraform-plan:
  stage: plan
  script:
    - echo "Planning Terraform changes for $TF_ENV environment..."
    - cd $TF_WORKING_DIR
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - $TF_WORKING_DIR/tfplan
  only:
    - master

terraform-apply:
  stage: apply
  script:
    - echo "Applying Terraform changes for $TF_ENV environment..."
    - cd $TF_WORKING_DIR
    - terraform apply -auto-approve tfplan
  when: manual
  only:
    - master